apiVersion: v1
kind: Template
metadata:
  name: aleph-jenkins-s2i-persistent
labels:
  template: aleph-jenkins-s2i-persistent
metadata:
  annotations:
    description: Creates a Jenkins master using S2I for installing plugins and configuring Jenkins
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: aleph-jenkins-s2i-persistent
parameters:
- description: Name of this particular instance.  Should be the name of the associated Bitbucket project.
  name: JENKINS_NAME
  required: true
- description: Git source URI for Jenkins S2I
  name: SOURCE_REPOSITORY_URL
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 1Gi
- description: Password for the Jenkins user.
  displayName: Jenkins Password
  generate: expression
  name: JENKINS_PASSWORD
  value: password
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: PVC name to attach to the pod for persistent storage
  displayName: PVC name
  name: PVC_NAME
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: jenkins
    name: ${JENKINS_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins
    name: ${JENKINS_NAME}
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: ${JENKINS_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${JENKINS_NAME}
    name: ${JENKINS_NAME}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${JENKINS_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${JENKINS_NAME}
    name: ${JENKINS_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${JENKINS_NAME}:latest
    resources:
      limits:
        memory: ${MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      secrets: []
      sourceSecret:
        name: "sshsecret"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins:1
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${JENKINS_NAME}
    name: ${JENKINS_NAME}
  spec:
    replicas: 1
    selector:
      app: ${JENKINS_NAME}
      deploymentconfig: ${JENKINS_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${JENKINS_NAME}
          deploymentconfig: ${JENKINS_NAME}
      spec:
        containers:
        - env:
          - name: JENKINS_PASSWORD
            value: ${JENKINS_PASSWORD}
          image: 172.30.166.151:5000/aleph-ci/${JENKINS_NAME}:latest
          imagePullPolicy: Always
          name: ${JENKINS_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: ${PVC_NAME}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: ${JENKINS_NAME}:latest
      type: ImageChange

